### ISSUE TITLE
Folder名稱空白字元問題

### ISSUE THREAD

**Issue by yiming330** [yiming330/pqi-istorage#4]
今天有發現如果Folder name有空白字元會有錯誤, file list 會列出folder, 但是folder name是空的

**Comment by mylivan** [comment]
I test with folder "space space", didn't find the problem. please provide your test steps and name pattern.

**Comment by yiming330** [comment]
中文字元也無法顯示

**Comment by yiming330** [comment]
做了測試. 如果在Mac create好的含空格(檔名前面或後面) 的file, 在Windows內還是可以正常讀取. 
如果在Windows內嘗試要create前或後有空格的檔名, Windows會自動做Trim的動作.

**Comment by yiming330** [comment]
Confirmed fixed. Closing the issue.
